name = "ITensorMPOConstruction"
uuid = "f1f99f3b-4b00-4d2f-a9c2-ce76efdc8f31"
authors = ["Ben Corbett and contributors"]
version = "0.1.0"

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
ITensorMPS = "0.1, 0.2"
ITensors = "0.3, 0.4, 0.5, 0.6, 0.7"
LinearAlgebra = "1.9, 1.10"
SparseArrays = "1.9, 1.10"
TimerOutputs = "0.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
